myName = input("What's you name?: ")
myAge = input("How old are you? :")
print("Gee, that's REALLY OLD")
replit = input("Do you like Replit?")
print("OF COURSE YOU DO!")
print()
print("So, you are")
print(myName)
print("and are the ripe old age of")
print(myAge)
print("and clearly think that Replit is")
print(replit)
my_variable = input("WHO GOES THERE? ")
print(my_variable)
myLunch = input("What are you having for lunch? ")
print("Hmm, it sounds like you really should just order")
print(myLunch)
print("as soon as possible!")
print("Definitely not a Phishing Scam")
print()
myName = input("Your Name")
print("Thanks for logging in")
print(myName)
cardNumber = input("What is your credit card number?")
print("Thanks, I definitely wont put")
print(cardNumber)
print("into Amazon and order anything weird")
print()
print("Promise")
maidenName = input("What is your Mother's maiden name? ")
print()
print("That's cool, I just wanted to know that")
print(maidenName)
print("was your Mum's maiden name. Not because the bank requested it or "
      "anything, honest.")


print("getting to know variables and input()\n")
print()
name = input("What is your name? ")
food = input("What is your favorite food? ")
song = input("What is your favorite song? ")
country = input("What country are you from? ")
print(f"Hello {name}. Your favorite food is {food}, you like the song {song}, and you are from {country}\n")
print(f"You are great {name}. Continue learning python")